# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\clairel\.qgis2\python\plugins\xgConstraintChecker\config_dialog_base.ui'
#
# Created: Tue Mar 27 16:03:07 2018
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_config_dialog(object):
    def setupUi(self, config_dialog):
        config_dialog.setObjectName(_fromUtf8("config_dialog"))
        config_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        config_dialog.resize(400, 608)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(config_dialog.sizePolicy().hasHeightForWidth())
        config_dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/xgConstraintChecker/checker_config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        config_dialog.setWindowIcon(icon)
        config_dialog.setModal(False)
        self.button_box = QtGui.QDialogButtonBox(config_dialog)
        self.button_box.setGeometry(QtCore.QRect(50, 550, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.grp_xgApps = QtGui.QGroupBox(config_dialog)
        self.grp_xgApps.setGeometry(QtCore.QRect(10, 10, 381, 141))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_xgApps.sizePolicy().hasHeightForWidth())
        self.grp_xgApps.setSizePolicy(sizePolicy)
        self.grp_xgApps.setObjectName(_fromUtf8("grp_xgApps"))
        self.lbl_xgApps = QtGui.QLabel(self.grp_xgApps)
        self.lbl_xgApps.setGeometry(QtCore.QRect(10, 20, 211, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_xgApps.sizePolicy().hasHeightForWidth())
        self.lbl_xgApps.setSizePolicy(sizePolicy)
        self.lbl_xgApps.setObjectName(_fromUtf8("lbl_xgApps"))
        self.txt_xgApps_local = QtGui.QPlainTextEdit(self.grp_xgApps)
        self.txt_xgApps_local.setGeometry(QtCore.QRect(10, 40, 361, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_xgApps_local.sizePolicy().hasHeightForWidth())
        self.txt_xgApps_local.setSizePolicy(sizePolicy)
        self.txt_xgApps_local.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_xgApps_local.setObjectName(_fromUtf8("txt_xgApps_local"))
        self.lbl_xgApps_network = QtGui.QLabel(self.grp_xgApps)
        self.lbl_xgApps_network.setGeometry(QtCore.QRect(10, 80, 231, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_xgApps_network.sizePolicy().hasHeightForWidth())
        self.lbl_xgApps_network.setSizePolicy(sizePolicy)
        self.lbl_xgApps_network.setObjectName(_fromUtf8("lbl_xgApps_network"))
        self.txt_xgApps_network = QtGui.QPlainTextEdit(self.grp_xgApps)
        self.txt_xgApps_network.setGeometry(QtCore.QRect(10, 100, 361, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_xgApps_network.sizePolicy().hasHeightForWidth())
        self.txt_xgApps_network.setSizePolicy(sizePolicy)
        self.txt_xgApps_network.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_xgApps_network.setObjectName(_fromUtf8("txt_xgApps_network"))
        self.grp_results_db = QtGui.QGroupBox(config_dialog)
        self.grp_results_db.setGeometry(QtCore.QRect(10, 160, 381, 381))
        self.grp_results_db.setObjectName(_fromUtf8("grp_results_db"))
        self.cbo_db_type = QtGui.QComboBox(self.grp_results_db)
        self.cbo_db_type.setGeometry(QtCore.QRect(100, 20, 121, 22))
        self.cbo_db_type.setObjectName(_fromUtf8("cbo_db_type"))
        self.cbo_db_type.addItem(_fromUtf8(""))
        self.cbo_db_type.addItem(_fromUtf8(""))
        self.cbo_db_type.addItem(_fromUtf8(""))
        self.lbl_db_type = QtGui.QLabel(self.grp_results_db)
        self.lbl_db_type.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lbl_db_type.setObjectName(_fromUtf8("lbl_db_type"))
        self.lbl_db = QtGui.QLabel(self.grp_results_db)
        self.lbl_db.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.lbl_db.setObjectName(_fromUtf8("lbl_db"))
        self.txt_db = QtGui.QPlainTextEdit(self.grp_results_db)
        self.txt_db.setGeometry(QtCore.QRect(100, 110, 271, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_db.sizePolicy().hasHeightForWidth())
        self.txt_db.setSizePolicy(sizePolicy)
        self.txt_db.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_db.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_db.setObjectName(_fromUtf8("txt_db"))
        self.txt_port = QtGui.QPlainTextEdit(self.grp_results_db)
        self.txt_port.setGeometry(QtCore.QRect(100, 80, 121, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_port.sizePolicy().hasHeightForWidth())
        self.txt_port.setSizePolicy(sizePolicy)
        self.txt_port.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_port.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_port.setObjectName(_fromUtf8("txt_port"))
        self.txt_host = QtGui.QPlainTextEdit(self.grp_results_db)
        self.txt_host.setGeometry(QtCore.QRect(100, 50, 271, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_host.sizePolicy().hasHeightForWidth())
        self.txt_host.setSizePolicy(sizePolicy)
        self.txt_host.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_host.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_host.setObjectName(_fromUtf8("txt_host"))
        self.lbl_port = QtGui.QLabel(self.grp_results_db)
        self.lbl_port.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.lbl_port.setObjectName(_fromUtf8("lbl_port"))
        self.lbl_host = QtGui.QLabel(self.grp_results_db)
        self.lbl_host.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.lbl_host.setObjectName(_fromUtf8("lbl_host"))
        self.grpLogin = QtGui.QGroupBox(self.grp_results_db)
        self.grpLogin.setGeometry(QtCore.QRect(10, 140, 361, 101))
        self.grpLogin.setObjectName(_fromUtf8("grpLogin"))
        self.chk_trusted = QtGui.QCheckBox(self.grpLogin)
        self.chk_trusted.setGeometry(QtCore.QRect(10, 20, 121, 17))
        self.chk_trusted.setObjectName(_fromUtf8("chk_trusted"))
        self.lbl_user = QtGui.QLabel(self.grpLogin)
        self.lbl_user.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.lbl_user.setObjectName(_fromUtf8("lbl_user"))
        self.lbl_pwd = QtGui.QLabel(self.grpLogin)
        self.lbl_pwd.setGeometry(QtCore.QRect(10, 70, 81, 20))
        self.lbl_pwd.setObjectName(_fromUtf8("lbl_pwd"))
        self.txt_user = QtGui.QPlainTextEdit(self.grpLogin)
        self.txt_user.setGeometry(QtCore.QRect(90, 40, 191, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_user.sizePolicy().hasHeightForWidth())
        self.txt_user.setSizePolicy(sizePolicy)
        self.txt_user.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_user.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_user.setPlainText(_fromUtf8(""))
        self.txt_user.setObjectName(_fromUtf8("txt_user"))
        self.txt_pwd = QtGui.QPlainTextEdit(self.grpLogin)
        self.txt_pwd.setGeometry(QtCore.QRect(90, 70, 191, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_pwd.sizePolicy().hasHeightForWidth())
        self.txt_pwd.setSizePolicy(sizePolicy)
        self.txt_pwd.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_pwd.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_pwd.setObjectName(_fromUtf8("txt_pwd"))
        self.grp_results_table = QtGui.QGroupBox(self.grp_results_db)
        self.grp_results_table.setGeometry(QtCore.QRect(10, 250, 361, 121))
        self.grp_results_table.setObjectName(_fromUtf8("grp_results_table"))
        self.lbl_table = QtGui.QLabel(self.grp_results_table)
        self.lbl_table.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.lbl_table.setObjectName(_fromUtf8("lbl_table"))
        self.txt_table = QtGui.QPlainTextEdit(self.grp_results_table)
        self.txt_table.setGeometry(QtCore.QRect(90, 50, 191, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_table.sizePolicy().hasHeightForWidth())
        self.txt_table.setSizePolicy(sizePolicy)
        self.txt_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_table.setPlainText(_fromUtf8(""))
        self.txt_table.setObjectName(_fromUtf8("txt_table"))
        self.rb_new = QtGui.QRadioButton(self.grp_results_table)
        self.rb_new.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rb_new.setChecked(True)
        self.rb_new.setObjectName(_fromUtf8("rb_new"))
        self.rb_existing = QtGui.QRadioButton(self.grp_results_table)
        self.rb_existing.setGeometry(QtCore.QRect(110, 20, 82, 17))
        self.rb_existing.setObjectName(_fromUtf8("rb_existing"))
        self.txt_geom = QtGui.QPlainTextEdit(self.grp_results_table)
        self.txt_geom.setGeometry(QtCore.QRect(90, 90, 191, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_geom.sizePolicy().hasHeightForWidth())
        self.txt_geom.setSizePolicy(sizePolicy)
        self.txt_geom.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_geom.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_geom.setPlainText(_fromUtf8(""))
        self.txt_geom.setObjectName(_fromUtf8("txt_geom"))
        self.lbl_geom = QtGui.QLabel(self.grp_results_table)
        self.lbl_geom.setGeometry(QtCore.QRect(10, 80, 61, 31))
        self.lbl_geom.setWordWrap(True)
        self.lbl_geom.setObjectName(_fromUtf8("lbl_geom"))

        self.retranslateUi(config_dialog)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), config_dialog.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), config_dialog.reject)
        QtCore.QObject.connect(self.cbo_db_type, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), config_dialog.enableDBFields)
        QtCore.QObject.connect(self.chk_trusted, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), config_dialog.enableLoginFields)
        QtCore.QObject.connect(self.rb_existing, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_table.setEnabled)
        QtCore.QObject.connect(self.rb_existing, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txt_geom.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(config_dialog)
        config_dialog.setTabOrder(self.txt_xgApps_local, self.txt_xgApps_network)
        config_dialog.setTabOrder(self.txt_xgApps_network, self.cbo_db_type)
        config_dialog.setTabOrder(self.cbo_db_type, self.txt_host)
        config_dialog.setTabOrder(self.txt_host, self.txt_port)
        config_dialog.setTabOrder(self.txt_port, self.txt_db)
        config_dialog.setTabOrder(self.txt_db, self.chk_trusted)
        config_dialog.setTabOrder(self.chk_trusted, self.txt_user)
        config_dialog.setTabOrder(self.txt_user, self.txt_pwd)
        config_dialog.setTabOrder(self.txt_pwd, self.rb_new)
        config_dialog.setTabOrder(self.rb_new, self.rb_existing)
        config_dialog.setTabOrder(self.rb_existing, self.txt_table)
        config_dialog.setTabOrder(self.txt_table, self.txt_geom)
        config_dialog.setTabOrder(self.txt_geom, self.button_box)

    def retranslateUi(self, config_dialog):
        config_dialog.setWindowTitle(_translate("config_dialog", "xgConstraintChecker Configuration", None))
        self.grp_xgApps.setTitle(_translate("config_dialog", "xgApps Folders", None))
        self.lbl_xgApps.setText(_translate("config_dialog", "Enter the path to the local xgApps folder:", None))
        self.lbl_xgApps_network.setText(_translate("config_dialog", "Enter the path to the network xgApps folder:", None))
        self.grp_results_db.setTitle(_translate("config_dialog", "Results Database", None))
        self.cbo_db_type.setItemText(0, _translate("config_dialog", "PostGIS", None))
        self.cbo_db_type.setItemText(1, _translate("config_dialog", "Spatialite", None))
        self.cbo_db_type.setItemText(2, _translate("config_dialog", "SQL Server", None))
        self.lbl_db_type.setText(_translate("config_dialog", "Database Type:", None))
        self.lbl_db.setText(_translate("config_dialog", "Database:", None))
        self.lbl_port.setText(_translate("config_dialog", "Port:", None))
        self.lbl_host.setText(_translate("config_dialog", "Host / Instance:", None))
        self.grpLogin.setTitle(_translate("config_dialog", "Login", None))
        self.chk_trusted.setText(_translate("config_dialog_base", "Trusted Connection", None))
        self.lbl_user.setText(_translate("config_dialog", "User:", None))
        self.lbl_pwd.setText(_translate("config_dialog", "Password:", None))
        self.grp_results_table.setTitle(_translate("config_dialog", "Results Table", None))
        self.lbl_table.setText(_translate("config_dialog", "Table name:", None))
        self.rb_new.setText(_translate("config_dialog", "Create new", None))
        self.rb_existing.setText(_translate("config_dialog", "Use existing", None))
        self.lbl_geom.setText(_translate("config_dialog", "Geometry column:", None))

import resources_rc
